package cn.javaer.snippets.model;

/**
 * {@link TreeNode} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractTreeNodeAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class TreeNodeAssert extends AbstractTreeNodeAssert<TreeNodeAssert, TreeNode> {

  /**
   * Creates a new <code>{@link TreeNodeAssert}</code> to make assertions on actual TreeNode.
   * @param actual the TreeNode we want to make assertions on.
   */
  public TreeNodeAssert(TreeNode actual) {
    super(actual, TreeNodeAssert.class);
  }

  /**
   * An entry point for TreeNodeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myTreeNode)</code> and get specific assertion with code completion.
   * @param actual the TreeNode we want to make assertions on.
   * @return a new <code>{@link TreeNodeAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static TreeNodeAssert assertThat(TreeNode actual) {
    return new TreeNodeAssert(actual);
  }
}
