package cn.javaer.snippets.box.model.pojo;

/**
 * {@link Areas} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractAreasAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class AreasAssert extends AbstractAreasAssert<AreasAssert, Areas> {

  /**
   * Creates a new <code>{@link AreasAssert}</code> to make assertions on actual Areas.
   * @param actual the Areas we want to make assertions on.
   */
  public AreasAssert(Areas actual) {
    super(actual, AreasAssert.class);
  }

  /**
   * An entry point for AreasAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myAreas)</code> and get specific assertion with code completion.
   * @param actual the Areas we want to make assertions on.
   * @return a new <code>{@link AreasAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static AreasAssert assertThat(Areas actual) {
    return new AreasAssert(actual);
  }
}
