package cn.javaer.snippets.spring.boot.autoconfigure.eclipse.collections.pojo;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link City} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractCityAssert<S extends AbstractCityAssert<S, A>, A extends City> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractCityAssert}</code> to make assertions on actual City.
   * @param actual the City we want to make assertions on.
   */
  protected AbstractCityAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual City's id is equal to the given one.
   * @param id the given id to compare the actual City's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual City's id is not equal to the given one.
   */
  public S hasId(Long id) {
    // check that actual City we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Long actualId = actual.getId();
    if (!Objects.areEqual(actualId, id)) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual City's name is equal to the given one.
   * @param name the given name to compare the actual City's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual City's name is not equal to the given one.
   */
  public S hasName(String name) {
    // check that actual City we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
